-- MAD MAX MIND GAME — GLOBAL LEADERBOARD
-- Run this entire script in Supabase SQL Editor.

create table if not exists public.mind_game_leaderboard (
  id bigint generated by default as identity primary key,
  player_name text not null,
  score integer not null default 0,
  level integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.mind_game_leaderboard enable row level security;

-- Public users can read the Top 10.
drop policy if exists "Anyone can view leaderboard"
on public.mind_game_leaderboard;

create policy "Anyone can view leaderboard"
on public.mind_game_leaderboard
for select
to anon
using (true);

-- The browser does NOT get direct insert/update permission.
-- Scores are submitted through the RPC function below.

create or replace function public.submit_mind_game_score(
  p_player_name text,
  p_score integer,
  p_level integer
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  existing_id bigint;
  existing_score integer;
begin
  p_player_name := trim(p_player_name);

  if char_length(p_player_name) < 2
     or char_length(p_player_name) > 20 then
    raise exception 'Invalid player name';
  end if;

  if p_score < 0 or p_score > 10000 then
    raise exception 'Invalid score';
  end if;

  if p_level < 1 or p_level > 10001 then
    raise exception 'Invalid level';
  end if;

  select id, score
  into existing_id, existing_score
  from public.mind_game_leaderboard
  where lower(player_name) = lower(p_player_name)
  limit 1;

  if existing_id is null then

    insert into public.mind_game_leaderboard
      (player_name, score, level)
    values
      (p_player_name, p_score, p_level);

  elsif p_score > existing_score then

    update public.mind_game_leaderboard
    set
      score = p_score,
      level = p_level,
      updated_at = now()
    where id = existing_id;

  end if;

  return json_build_object(
    'success', true,
    'player_name', p_player_name,
    'score', p_score,
    'level', p_level
  );
end;
$$;

revoke all on function public.submit_mind_game_score(text, integer, integer)
from public;

grant execute on function public.submit_mind_game_score(text, integer, integer)
to anon;
